import SSRProvider from "react-bootstrap/SSRProvider";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";

declare global {
  namespace JSX {
    interface IntrinsicElements {
      ["webout-player"]: any;
    }
  }
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SSRProvider>
      <div id="all-wrapper">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script
            src="https://cdn.webout.me/webout-player.42edf2c80b9a18176010.js"
            defer
          ></script>
        </Head>
        <Component {...pageProps} />
      </div>
    </SSRProvider>
  );
}

export default MyApp;
